# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Admin/Documents/Vivado/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Documents/Vivado/Lab6/Lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Admin/Documents/Vivado/Lab6/Lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/clk_50m_generator.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/fifo.v
  C:/Users/Admin/Documents/Vivado/Lab5/Lab5.srcs/sources_1/new/font_rom.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/kb_monitor.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/mod_m_counter.v
  C:/Users/Admin/Documents/Vivado/Lab5/Lab5.srcs/sources_1/new/pong_graph_animate.v
  C:/Users/Admin/Documents/Vivado/Lab5/Lab5.srcs/sources_1/new/pong_text.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/ps2_rx.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/uart.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/uart_rx.v
  C:/Users/Admin/Documents/Vivado/Lab6/Lab6.srcs/sources_1/new/uart_tx.v
  C:/Users/Admin/Documents/Vivado/Lab5/Lab5.srcs/sources_1/new/vga_sync.v
  C:/Users/Admin/Documents/Vivado/Lab5/Lab5.srcs/sources_1/new/pong_top_an.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Admin/Documents/Vivado/Lab6/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Admin/Documents/Vivado/Lab6/Nexys4_Master.xdc]


synth_design -top pong_top_an -part xc7a100tcsg324-1


write_checkpoint -force -noxdef pong_top_an.dcp

catch { report_utilization -file pong_top_an_utilization_synth.rpt -pb pong_top_an_utilization_synth.pb }
